import 'text_chunk.dart';

/// Stores the vector representation of a text chunk.
///
/// Week 6 currently uses a lightweight term-frequency vector.
/// In later development, the vector can be replaced by an embedding
/// generated by a neural model such as BERT or TensorFlow Lite.
class EmbeddingVector {
  /// The original text chunk represented by this vector.
  final TextChunk chunk;

  /// Ordered vocabulary used to build the vector.
  final List<String> vocabulary;

  /// Numerical vector values corresponding to the vocabulary.
  final List<double> values;

  /// Time when the vector was generated.
  final DateTime generatedAt;

  EmbeddingVector({
    required this.chunk,
    required this.vocabulary,
    required this.values,
    required this.generatedAt,
  });

  /// Number of dimensions in the vector.
  int get dimension => values.length;

  /// Returns true when every vector value is zero.
  bool get isZeroVector => values.every((value) => value == 0.0);

  @override
  String toString() {
    return 'EmbeddingVector('
        'file: ${chunk.sourceFileName}, '
        'chunkIndex: ${chunk.chunkIndex}, '
        'dimension: $dimension, '
        'generatedAt: $generatedAt'
        ')';
  }
}